#!/bin/bash

# if user has requested UPDATE_YOUTUBE_DL, then update youtube-dl
if [[ -n "$UPDATE_YOUTUBE_DL" ]]; then
    echo "Attempting update of youtube-dl"
    python3 -m pip install --upgrade --no-cache-dir yt-dlp 2>&1 | grep -v WARNING
fi

# Set UID/PID of user that youtube-dl will be run as
YOUTUBEDLPGID=${PGID:-1000}
YOUTUBEDLPUID=${PUID:-1000}

# Check to see if group/user already exist, if so, delete
EXISTINGGROUPNAME=$(getent group "$YOUTUBEDLPGID" | cut -d ':' -f 1)
EXISTINGUSERNAME=$(getent passwd "$YOUTUBEDLPUID" | cut -d ':' -f 1)
if [[ -n "$EXISTINGGROUPNAME" ]]; then
    groupdel -f "$EXISTINGGROUPNAME"
fi
if [[ -n "$EXISTINGUSERNAME" ]]; then
    userdel -f "$EXISTINGUSERNAME"
fi

# Create user/group
addgroup --quiet --gid "$YOUTUBEDLPGID" dockeruser
chown -R "$YOUTUBEDLPUID":"$YOUTUBEDLPGID" /home/dockeruser
adduser --quiet --system --disabled-password --uid "$YOUTUBEDLPUID" --gid "$YOUTUBEDLPGID" --home /home/dockeruser dockeruser
chown -R "$YOUTUBEDLPUID":"$YOUTUBEDLPGID" /usr/local/bin/yt-dlp
chmod u+s /usr/local/bin/yt-dlp
HOME=/home/dockeruser
export HOME

# Set UMASK if required
if [[ -n "$UMASK" ]]; then
    umask "$UMASK"
fi

# Run youtube-dlc with remainder of command line arguments
setpriv --reuid dockeruser --regid dockeruser --keep-groups python3 /usr/local/bin/yt-dlp "$@"
